### PR TITLE
[Evaluation] [Performance] Ditch 'NamedDeBruijn' in favor of 'DeBruijn'

### PR DESCRIPTION
**Pull request by effectfully**
Let's see how much these nasty name conversions cost us.

### CODE REVIEW

**Comment by kwxm** [comment]
Those results look pretty conclusive!

**Comment by effectfully** [comment]
OK, I'm a moron, `validation` benchmarks don't include the preparation costs. It's still wild that we get a slowdown here, as if `toNamedDeBruijn` was forcing something important that somehow isn't forced by `force`. Weird.

**Comment by effectfully** [comment]
WTF is going on in this PR

image

**Comment by effectfully** [comment]
> WTF is going on in this PR

And it is consistent, here's the second output:

Screenshot from 2024-11-28 10-46-51

and the third one:

Screenshot from 2024-11-28 10-47-18

It appears that this PR somehow slows down the evaluator, while speeding up preparation, hence why we see results all over the place. How can it possibly slow down the evaluator? I have no idea, but this is likely me screwing something up, because I can't think of a way to make things slower by removing redundant code.

**Pull request closed without merging**
