### PR TITLE
[Evaluation] Use 'lookupInline'

### PR DESCRIPTION
**Pull request by effectfully**
Don't look here yet.

### CODE REVIEW

**Comment by kwxm** [comment]
^ That's kind of what I was expecting, but I thought it was worth checking.  Most of the work in these is spent on CPU-intensive library functions.

**Comment by effectfully** [comment]
CPU performance isn't that big of a deal anymore and what we can get here should be fairly insignificant, so I added it to the [epic](https://github.com/IntersectMBO/plutus/issues/5955) and let's close it for now.

**Pull request closed without merging**
