### PR TITLE
[Builtins] Store 'BuiltinRuntime' lazily explicitly

### PR DESCRIPTION
**Pull request by effectfully**
This allows us to be more precise regarding how `BuiltinRuntime`s are stored and it allows us to implement a proper `NoThunks` instance for `BuiltinsRuntime` at the cost of introducing an indirection that slightly slows things down at runtime (may be undetectable, but let's see).

This is an EXPERIMENT, do not merge.

### CODE REVIEW

**Comment by effectfully** [comment]
^ -3.15% on average lol.

**Comment by effectfully** [comment]
^ -2.18%. I don't believe it.

image

**Comment by effectfully** [comment]
^ -2.84%. Ok, I'll look into it. I don't trust it still.

**Comment by effectfully** [comment]
^ +1.76% on average.

**Comment by kwxm** [comment]
> ^ -2.18%. I don't believe it.

Quick!  Merge it!

**Comment by effectfully** [comment]
I thought this wouldn't be compatible with extensible cost models in the end, but it is compatible. Still GHC-8.10 doesn't like something. I'm closing this for now and I've added an entry about this issue to #4306 in case we want to return to it in future.

**Pull request closed without merging**
