### PR TITLE
[AST] [Evaluation] Use 'SmallArray' in 'Case'

### PR DESCRIPTION
**Pull request by effectfully**
Another competitor. Previous in the series: #5818, #5813, #5816.

### CODE REVIEW

**Comment by michaelpj** [comment]
Looks like `Vector` is faster? Could be measurement error, but the difference looks big and consistent enough to be real?

**Comment by effectfully** [comment]
> Looks like `Vector` is faster? Could be measurement error, but the difference looks big and consistent enough to be real?

Yes, let me rerun and check the diff again, but otherwise `Vector` is clearly better, which I find really surprising. Maybe it's fusion that's kicking in somehow.

**Comment by michaelpj** [comment]
I'll rebase my branch and rerun the benchmarks in case something has changed

**Comment by effectfully** [comment]
CPU performance isn't that big of a deal anymore and what we can get here should be fairly insignificant, so I added it to the [epic](https://github.com/IntersectMBO/plutus/issues/5955) and let's close it for now.

**Pull request closed without merging**
