### PR TITLE
Replace stylish-haskell with fourmolu

### PR DESCRIPTION
**Pull request by ana-pantilie**
Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Changelog fragments have been written (if appropriate)
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, PNG optimization, etc. are updated
- PR
    - [ ] (For external contributions) Corresponding issue exists and is linked in the description
    - [ ] Targeting master unless this is a cherry-pick backport
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] Reviewer requested

### CODE REVIEW

**Review by Unisay — APPROVED** [review]
Thanks!

**Comment by ana-pantilie** [comment]
@Unisay looks like we also have to disable the `fourmolu` part of the `pre-commit-check` which runs as a separate workflow on all the files

**Comment by zliu41** [comment]
I don't think we are ready to do this, are we? This means if anyone opens a PR that touches an unformatted file, it will be reformatted, potentially making the code review much harder.

**Comment by ana-pantilie** [comment]
@zliu41 I thought we wanted to do this incrementally meaning, if I am working on some part of the codebase I also format it. Yes, this will result in a lot of noise concerning the diff.

If we don't want noise in diffs, then we'll have to do the reformatting in one go, but we decided against that (I don't remember why, though).

**Comment by zliu41** [comment]
I suggest we do neither. Instead, let's format 10 modules at a time, and try picking 10 modules that nobody is actively working on.

**Comment by ana-pantilie** [comment]
Uff, @Unisay asked me to format my PR with fourmolu, or maybe I misunderstood. I thought this meant we decided to format things as we go.

**Comment by ana-pantilie** [comment]
In any case, even picking 10 modules at a time in separate PRs won't work without also messing with the commit precheck. If we don't disable stylish-haskell then it will end up running over the files formatted with fourmolu. If we disable stylish and enable fourmolu, then there's this _other_ job which runs the precheck on the whole repo.

**Comment by zliu41** [comment]
It shouldn't be very difficult
- add `{- FOURMOLU_DISABLE -}` to every `.hs` file
- disable stylish and enable fourmolu in precheck
- reformat 10 modules at a time and remove `{- FOURMOLU_DISABLE -}` after reformatting

**Pull request closed without merging**
