### PR TITLE
Update iohk-nix to include the new blst version.

### PR DESCRIPTION
**Pull request by angerman**

### CODE REVIEW

**Comment by michaelpj** [comment]
Windows cross seems to be broken? Perhaps we need a newer haskell.nix?

**Comment by michaelpj** [comment]
I made https://github.com/IntersectMBO/plutus/pull/5809 to bump everything

**Comment by kwxm** [comment]
Thanks.  I think this'll fix the problem that I had earlier.  It'll also let us get up-to-date costs for the BLS operations.

**Comment by angerman** [comment]
fixed in #5809 instead.

**Pull request closed without merging**
