### PR TITLE
Bump all our flake inputs

### PR DESCRIPTION
**Pull request by michaelpj**

### CODE REVIEW

**Comment by kwxm** [comment]
Nix takes a _really_ long time to start up with this!

**Comment by michaelpj** [comment]
It's probably building some GHCs :see_no_evil:

**Comment by kwxm** [comment]
`nix develop` fails in this branch:
```
error: builder for '/nix/store/rjw0cjkg4pd3f7hax0bvacibxwg71pvv-ghcide-lib-ghcide-2.4.0.0.drv' failed with exit code 1;
       last 10 log lines:
       > 225 |            in notFound {fr_unusables = unusables'}
       >     |                                        ^^^^^^^^^^
       > [35 of 74] Compiling Development.IDE.GHC.Warnings ( src/Development/IDE/GHC/Warnings.hs, dist/build/Development/IDE/GHC/Warnings.o, dist/build/Development/IDE/GHC/Warnings.dyn_o )
       > [36 of 74] Compiling Development.IDE.Core.Tracing ( src/Development/IDE/Core/Tracing.hs, dist/build/Development/IDE/Core/Tracing.o, dist/build/Development/IDE/Core/Tracing.dyn_o )
       > [37 of 74] Compiling Development.IDE.Core.Preprocessor ( src/Development/IDE/Core/Preprocessor.hs, dist/build/Development/IDE/Core/Preprocessor.o, dist/build/Development/IDE/Core/Preprocessor.dyn_o )
       > [38 of 74] Compiling Development.IDE.Types.Monitoring ( src/Development/IDE/Types/Monitoring.hs, dist/build/Development/IDE/Types/Monitoring.o, dist/build/Development/IDE/Types/Monitoring.dyn_o )
       > [39 of 74] Compiling Development.IDE.Monitoring.OpenTelemetry ( src/Development/IDE/Monitoring/OpenTelemetry.hs, dist/build/Development/IDE/Monitoring/OpenTelemetry.o, dist/build/Development/IDE/Monitoring/OpenTelemetry.dyn_o )
       > [40 of 74] Compiling Development.IDE.Monitoring.EKG ( src/Development/IDE/Monitoring/EKG.hs, dist/build/Development/IDE/Monitoring/EKG.o, dist/build/Development/IDE/Monitoring/EKG.dyn_o )
       > [69 of 74] Compiling Generics.SYB.GHC ( src/Generics/SYB/GHC.hs, dist/build/Generics/SYB/GHC.o, dist/build/Generics/SYB/GHC.dyn_o )
       > [70 of 74] Compiling Text.Fuzzy.Parallel ( src/Text/Fuzzy/Parallel.hs, dist/build/Text/Fuzzy/Parallel.o, dist/build/Text/Fuzzy/Parallel.dyn_o )
       For full logs, run 'nix log /nix/store/rjw0cjkg4pd3f7hax0bvacibxwg71pvv-ghcide-lib-ghcide-2.4.0.0.drv'.
error: 1 dependencies of derivation '/nix/store/skbz5f9gfq63fpnjm6yh8crbrsg02lrp-haskell-language-server-exe-haskell-language-server-2.4.0.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/nfrk58pcbsdjf4lz5nsvxvkmq6lv1afs-ghc-shell-for-packages-env.drv' failed to build
```

**Comment by michaelpj** [comment]
Needs a newer HLS. Fixed upstream in https://github.com/input-output-hk/iogx/pull/43, let's see if that gets in soonish.

**Pull request merged**
